config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :applications
  resources :jobs
  
  get '/register', to: "users#new"
  get '/my', to: "applications#my"
  root  to: "welcome#index"

  # Session Routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
end

app/models/application.rb
class Application < ApplicationRecord
    belongs_to :user
    belongs_to :job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

# Authrized   
include Pundit
rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

private

def user_not_authorized
  flash[:alert] = "You are not authorized to perform this action."
  redirect_to(request.referrer || '/')
end
#End Authrized


helper_method :current_user, :logged_in?
def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def current_user_role
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

 
def logged_in?
  !!current_user
end
 
def require_user
  if !logged_in?
    flash[:alert] = "You must be logged in to perform that action."
    redirect_to login_path
  end
end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: %i[ show edit update destroy ]

  # GET /applications or /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1 or /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end


   # GET /applications/my
   def my
    if !logged_in?
      redirect_to  ('/login')
    return;
    end
     @applications = Application.where(user_id: current_user.id).order(created_at: :desc)
    end
  # GET /applications/1/edit
  def edit
  end

  # POST /applications or /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: "Application was successfully Sent." }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: "Application was successfully updated." }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def application_params
      params.require(:application).permit(:user_id, :job_id, :seen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_with(model: application) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
        <% application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :job_id %>
    <%= form.number_field :job_id %>
  </div>

  <div class="field">
    <%= form.label :seen %>
    <%= form.check_box :seen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applications</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Job</th>
      <th>Seen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.user_id %></td>
        <td><%= application.job_id %></td>
        <td><%= application.seen %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
      <!--   <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/my.html.erb
<h1>My Applicatios</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Job</th>
      <th>Seen</th>
      <th>Submitted at</th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= Job.find(application.job_id).title %>    </td>
        <td>    <%= application.seen ? 'Yes':'No' %></td>
           <td>    <%= time_ago_in_words(application.created_at)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<div class = "text-center">
  <div class = "card success">


  <div class="svg-container">    
      <svg class="ft-green-tick" xmlns="http://www.w3.org/2000/svg" height="100" width="100" viewBox="0 0 48 48" aria-hidden="true">
          <circle class="circle" fill="#5bb543" cx="24" cy="24" r="22"/>
          <path class="tick" fill="none" stroke="#FFF" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M14 27l5.917 4.917L34 17"/>
      </svg>
  </div>
  <br>
    <p id="notice"><%= notice %></p>

  <p>
    <strong>User:</strong><%=   User.find(@application.user_id).username%>
  </p>

  <p>
    <strong>Job:</strong>
  <%=   Job.find(@application.job_id ).title%>
  </p>

  <p>
    <strong>Seen:</strong>
    <%= @application.seen ? 'Yes':'No' %>
  </p>

  <!--  <%= link_to 'Edit', edit_application_path(@application) %> -->
  <!-- <%= link_to 'Back', applications_path %> -->
  </div>
</div>