config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :applications
  resources :jobs
  
  get '/register', to: "users#new"
  get '/my', to: "applications#my"
  root  to: "welcome#index"

  # Session Routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :applications, dependent: :destroy
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    #@jobs = Job.all.order(created_at: :desc)
    @jobs = Job.where(" expiry_date >= ?", Date.today).order(created_at: :desc)

    if !logged_in?
       redirect_to  ('/login')
     return;
    end
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    if !logged_in?
      redirect_to  ('/login')
    return;
    end
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description,:location, :salary, :fullTime, :expiry_date )
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job,  :html => {:class => 'login-register-form' }) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title ,:class => 'form-control' %>
  </div>
   <div class="field form-group">
    <%= form.label :salary %>
    <%= form.text_field :salary ,:class => 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description ,:class => 'form-control' %>
  </div>
  
  <div class="field form-group">
    <%= form.label :location %>
    <%= form.text_field :location  ,:class => 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :fullTime %>
    <%= form.check_box :fullTime %>
  </div>

   <div class="field form-group">
    <%= form.label :expiry_date %>
   <%= form.date_field :expiry_date, :id => "datepicker" ,:class => 'form-control' %>


  </div>
 
   <div class="actions field form-group">
    <%= form.submit   :class => 'btn w-100 pt-20 pb-20'  %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
        <!-- Job List Area Start -->
        <div class="job-listing-area   pb-120">
            <div class="container">
                <div class="row">
                    <!-- Left content -->
                    <div class="col-xl-3 col-lg-3 col-md-4">
                        <div class="row">
                            <div class="col-12">
                                    <div class="small-section-tittle2 mb-45">
                                    <div class="ion"> <svg 
                                        xmlns="http://www.w3.org/2000/svg"
                                        xmlns:xlink="http://www.w3.org/1999/xlink"
                                        width="20px" height="12px">
                                    <path fill-rule="evenodd"  fill="rgb(27, 207, 107)"
                                        d="M7.778,12.000 L12.222,12.000 L12.222,10.000 L7.778,10.000 L7.778,12.000 ZM-0.000,-0.000 L-0.000,2.000 L20.000,2.000 L20.000,-0.000 L-0.000,-0.000 ZM3.333,7.000 L16.667,7.000 L16.667,5.000 L3.333,5.000 L3.333,7.000 Z"/>
                                    </svg>
                                    </div>
                                    <h4>Filter Jobs</h4>
                                </div>
                            </div>
                        </div>
                        <!-- Job Category Listing start -->
                        <div class="job-category-listing mb-50">
                            <!-- single one -->
                            <div class="single-listing">
                               <div class="small-section-tittle2">
                                     <h4>Job Category</h4>
                               </div>
                                <!-- Select job items start -->
                                <div class="select-job-items2">
                                    <select name="select">
                                        <option value="">All Category</option>
                                        <option value="">Category 1</option>
                                        <option value="">Category 2</option>
                                        <option value="">Category 3</option>
                                        <option value="">Category 4</option>
                                    </select>
                                </div>
                                <!--  Select job items End-->
                                <!-- select-Categories start -->
                                <div class="select-Categories pt-80 pb-50">
                                    <div class="small-section-tittle2">
                                        <h4>Job Type</h4>
                                    </div>
                                    <label class="container">Full Time
                                        <input type="checkbox" >
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Part Time
                                        <input type="checkbox" checked="checked active">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Remote
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Freelance
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                            <!-- single two -->
                            <div class="single-listing">
                               <div class="small-section-tittle2">
                                     <h4>Job Location</h4>
                               </div>
                                <!-- Select job items start -->
                                <div class="select-job-items2">
                                    <select name="select">
                                        <option value="">Anywhere</option>
                                        <option value="">Category 1</option>
                                        <option value="">Category 2</option>
                                        <option value="">Category 3</option>
                                        <option value="">Category 4</option>
                                    </select>
                                </div>
                                <!--  Select job items End-->
                                <!-- select-Categories start -->
                                <div class="select-Categories pt-80 pb-50">
                                    <div class="small-section-tittle2">
                                        <h4>Experience</h4>
                                    </div>
                                    <label class="container">1-2 Years
                                        <input type="checkbox" >
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">2-3 Years
                                        <input type="checkbox" checked="checked active">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">3-6 Years
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">6-more..
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                            <!-- single three -->
                            <div class="single-listing">
                                <!-- select-Categories start -->
                                <div class="select-Categories pb-50">
                                    <div class="small-section-tittle2">
                                        <h4>Posted Within</h4>
                                    </div>
                                    <label class="container">Any
                                        <input type="checkbox" >
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Today
                                        <input type="checkbox" checked="checked active">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Last 2 days
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Last 3 days
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Last 5 days
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Last 10 days
                                        <input type="checkbox">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                            <div class="single-listing">
                                <!-- Range Slider Start -->
                             
                            </div>
                        </div>
                        <!-- Job Category Listing End -->
                    </div>
                    <!-- Right content -->
                    <div class="col-xl-9 col-lg-9 col-md-8">
                    <span class='float-right'><%= link_to 'Add Job (wait auth)', new_job_path ,:class => 'btn-new-job' %></span>
                        <!-- Featured_job_start -->
                        <section class="featured-job-area">
                            <div class="container">
                                <!-- Count of Job list Start -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="count-job mb-35">
                                            <span> <%=  @jobs.count %>  Jobs found</span>
                                            <!-- Select job items start -->
                                           
                                            <!--  Select job items End-->
                                        </div>
                                    </div>
                                </div>
                                <!-- Count of Job list End -->
                               <% @jobs.each do |job| %>
    
   
                                <!-- single-job-content -->
                                <div class="single-job-items mb-30">
                                    <div class="job-items">
                                        <div class="company-img">
                                            <a href="#"><img src="assets/img/icon/job-list4.png" alt=""></a>
                                        </div>
                                        <div class="job-tittle job-tittle2">
                                           <%=  User.find(3).username  %>
                                        
                                         
                                        
                                               <h4> <%= link_to job.title, job %>  </h4>
                                             <ul>
                                                <li><%= job.description %></li>
                                                <li><i class="fas fa-map-marker-alt"></i><%= job.location %></li>
                                                <li><%=
                                                if job.salary? 
                                                '$'+job.salary 
                                                else '-'
                                                end
                                              %></li>

                                              <li><%=
                                                if job.fullTime? 
                                                'Full Time'
                                                else 'Part Time'
                                                end
                                              %></li>

                                            </ul>
                                        </div>
                                    </div>
     
                                    <div class="items-link items-link2 f-right">
                                         
                                         <%= form_for(:application, :url =>  applications_url) do |f| %>
                                           <div class="field">
                                            
                                            <%= f.hidden_field  :job_id ,  :value => job.id %>
                                             <%= f.hidden_field  :user_id , :value => current_user.id%>
                                           
                                             <%= f.submit   :value =>  'Apply Now',:class => 'btn'  %>
                                          </div>
                                          <% end %>
                                        <span> <i class="fas fa-clock"></i> <%=  time_ago_in_words (job.created_at) %></span>
                                    </div>
                                </div>
                                 <% end %>
                                <!-- End single job -->
                            </div>
                        </section>
                        <!-- Featured_job_end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Job List Area End -->
        
    

 
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>
<!--
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 -->

app/views/jobs/new.html.erb
<h1 class = 'text-center' >Create New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<div class = "text-center">
    <div class = "card success">
    <p id="notice"><%= notice %></p>
    <div class="svg-container">    
        <svg class="ft-green-tick" xmlns="http://www.w3.org/2000/svg" height="100" width="100" viewBox="0 0 48 48" aria-hidden="true">
            <circle class="circle" fill="#5bb543" cx="24" cy="24" r="22"/>
            <path class="tick" fill="none" stroke="#FFF" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M14 27l5.917 4.917L34 17"/>
        </svg>
    </div>
    <p>
      <strong>Title:</strong>
      <%= @job.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @job.description %>
    </p>
    <p>
      <strong>Location:</strong>
      <%= @job.location %>
    </p>
    

    <%= link_to 'Edit', edit_job_path(@job) %> |
    <%= link_to 'Back', jobs_path %>
    </div>
</div>