config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :applications
  resources :jobs
  
  get '/register', to: "users#new"
  get '/my', to: "applications#my"
  root  to: "welcome#index"

  # Session Routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :applications, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.order(created_at: :desc)
    #authorize @users
  #  if current_user.has_role? :admin
  # @users = User.all
  #  else
  #  redirect_to  ('/login')
  # end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Successfully Registered." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :role, :role_id )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_area :password %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.role == '1'? 'Admin':'Seeker' %></td>
       <!--  <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true,  :html => {:class => 'login-register-form' }) do |f| %>
 <h1 class ='text-center' >Create an Account</h1>
<div class="form-group">
  <%= f.label :username %><br/>
  <%= f.text_field :username, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.label :email %><br/>
  <%= f.email_field :email, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.label :password %><br/>
  <%= f.password_field :password, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.submit "Register", class: "btn btn-primary pt-20 pb-20 w-100" %>
</div>

<% end %>

app/views/users/show.html.erb
<div class = "text-center">
    <div class = "card success">
    <p id="notice"><%= notice %></p>
    <div class="svg-container">    
        <svg class="ft-green-tick" xmlns="http://www.w3.org/2000/svg" height="100" width="100" viewBox="0 0 48 48" aria-hidden="true">
            <circle class="circle" fill="#5bb543" cx="24" cy="24" r="22"/>
            <path class="tick" fill="none" stroke="#FFF" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M14 27l5.917 4.917L34 17"/>
        </svg>
    </div>  
  </div>
 <!--  for admin -->
    <span  class='btn head-btn2'>
      <%= link_to 'Login Now', login_path %>
    </span>
<%= link_to 'Edit', edit_user_path(@user) %> |