config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :applications
  resources :jobs
  
  get '/register', to: "users#new"
  get '/my', to: "applications#my"
  root  to: "welcome#index"

  # Session Routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
	<!-- CSS here -->
        
         <%= stylesheet_link_tag("/assets/jobs/css/bootstrap.min.css") %>
         <%= stylesheet_link_tag("/assets/jobs/css/style.css") %>
         <%= stylesheet_link_tag("/assets/jobs/css/fontawesome-all.min.css") %>

    
	<!-- JS here -->
	
	 
		<!-- Jquery, Popper, Bootstrap -->
     <%= javascript_include_tag ("/assets/jobs/js/vendor/jquery-1.12.4.min.js") %>
  	<%= javascript_include_tag ("/assets/jobs/js/popper.min.js") %>
  	<%= javascript_include_tag ("/assets/jobs/js/bootstrap.min.js") %>
 
         
         	<%= javascript_include_tag ("/assets/jobs/js/main.js") %>
   
  </head>

  <body>
   

   <body>
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="https://d2is554mdy16bu.cloudfront.net/assets/zenhr-header-logo-eb82b4c0133ab581dbd9a7121464340445d3d1f8d47ef7e7bcc814c256807333.svg" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
       <div class="header-area header-transparrent">
           <div class="headder-top header-sticky">
                <div class="container ">
                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-2">
                            <!-- Logo -->
                            <div class="logo">
                                <a href="/"><img src="https://d2is554mdy16bu.cloudfront.net/assets/zenhr-header-logo-eb82b4c0133ab581dbd9a7121464340445d3d1f8d47ef7e7bcc814c256807333.svg" alt=""></a>
                            </div>  
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <div class="menu-wrapper">
                                <!-- Main-menu -->
                                <div class="main-menu">
                                    <nav class="d-none d-lg-block">
                                        <ul id="navigation">
                                            <li><a href="/">Home</a></li>
                                            <li><a href="/jobs">Find a Jobs </a></li>
                                            <li><a href="#about">About</a></li>
                                            
                                            <li><a href="#contact">Contact</a></li>
                                            <% if logged_in? %>
                                             
                                              <span class="btn head-btn2"> <%= link_to "My Applications", my_path %>  </span>
                                             
                                            <%end%> 
                                        </ul>
                                    </nav>
                                </div>          
                                <!-- Header-btn -->
                                <div class="header-btn d-none f-right d-lg-block">
                                <% if !logged_in? %>
                                    <a href="/register" class="btn head-btn1">Register</a>
                                 <%end%>  
                                 <% if !logged_in? %>
                                    <span class="btn head-btn2"> <%= link_to "Login", login_path %>  </span>
                                  <%end%> 
                                 <% if logged_in? %>
                                    <a href="#" class="btn head-btn1">Hi, <%= current_user.username %></a>
                                 <%end%>   

                                 <% if logged_in? %>
                                    <span class="btn head-btn2"> <%= link_to "Log out", logout_path %>  </span>
                                  <%end%> 


                                    
                                </div>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
           </div>
       </div>
        <!-- Header End -->
    </header>
    
    <main>
    <div class = "container content">
      <%= yield %>
    </div>
    
        
    </main>
    <footer>
        <!-- Footer Start-->

        <!-- footer-bottom area -->
        <div class="footer-bottom-area footer-bg">
            <div class="container ">
                <div class="footer-border">
                     <div class="row d-flex justify-content-between align-items-center">
                         <div class="col-xl-10 col-lg-10 ">
                             <div class="footer-copy-right">
                                 <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://www.zenhr.com/" target="_blank">ZenHR</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                             </div>
                         </div>
                         <div class="col-xl-2 col-lg-2">
                             <div class="footer-social f-right">
                                 <a href="#"><i class="fab fa-facebook-f"></i></a>
                                 <a href="#"><i class="fab fa-twitter"></i></a>
                                 <a href="#"><i class="fas fa-globe"></i></a>
                                 <a href="#"><i class="fab fa-behance"></i></a>
                             </div>
                         </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>



  </body>
</html>